synaptics_dsx_force: Fix uninitialized variable
Clang warns:
drivers/input/touchscreen/synaptics_dsx_force/synaptics_dsx_i2c.c:766:19: error:
      variable 'retval' is used uninitialized whenever 'for' loop exits
      because its condition is false [-Werror,-Wsometimes-uninitialized]
                for (retry = 0; retry < SYN_I2C_RETRY_TIMES; retry++) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/input/touchscreen/synaptics_dsx_force/synaptics_dsx_i2c.c:788:9: note:
      uninitialized use occurs here
        return retval;
               ^~~~~~
drivers/input/touchscreen/synaptics_dsx_force/synaptics_dsx_i2c.c:766:19: note:
      remove the condition if it is always true
                for (retry = 0; retry < SYN_I2C_RETRY_TIMES; retry++) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/input/touchscreen/synaptics_dsx_force/synaptics_dsx_i2c.c:749:12: note:
      initialize the variable 'retval' to silence this warning
        int retval;
                  ^
                   = 0
1 error generated