ASoC: msm: qdsp6v2: Fix non-literal-null-conversion warning
../sound/soc/msm/qdsp6v2/q6lsm.c:255:33: error: expression which evaluates to zero treated as a null pointer constant of type 'struct lsm_client *' [-Werror,-Wnon-literal-null-conversion]
        lsm_session[client->session] = LSM_INVALID_SESSION_ID;
                                       ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: yarost12 <yaro330@gmail.com>
Signed-off-by: Albert I <krascgq@outlook.co.id>
[@nathanchance: Improve changelog text]
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

(cherry picked from commit 1c721ad84969c6023df04a244087f345a50e1ffd)
(cherry picked from commit 99fbc895363c21d8f284530c7bc514af69004cb6)